### ISSUE TITLE
Add a way to import konnector data

### ISSUE THREAD

**Issue by Peltoche** [cozy/ACH#135]
Hi!

I have written a konnector locally and after a successfull run I have a `data` folder with an `importedData.json` inside of it. I have successfully uploaded the files with the command `ACH importDir` but I didn't find a way to import the files *with the corresponding metadata*. 

Would it be possible to add an helper script or and example for the case please?

**Comment by doubleface** [comment]
Hi! You can run your connector in dev mode to have the data directly imported in your cozy.

You can follow https://docs.cozy.io/en/tutorials/konnector/save-data/#linking-your-connector-to-a-cozy-dev-mode

**Comment by Peltoche** [comment]
Nice! Didn't know this mode. Thanks for the tip!
