### ISSUE TITLE
Add a default limit for batch

### ISSUE THREAD

**Issue by cedricmessiant** [cozy/ACH#42]
We could add a default limit for batch mode to be more defensive and avoid to run scripts that take lots of resources (like I did yesterday on `.rocks` env :disappointed: )

What do you think ? Do you think that it's the user's responsibility to know if he has to use the limit option or not? Also, what would be a good value for this?

**Comment by ptbrowne** [comment]
There is a PromisePool in place that throttles the scripts to 30 at the same time. 

What kind of other limit do you think is necessary ?

**Comment by cedricmessiant** [comment]
Oh, sorry about that, I misread the code. I thought that le `--limit` option was used for this.

**Comment by ptbrowne** [comment]
Just to be sure @nono , I remember that we have had trouble with parallelism and token generation. Is 30 token generation not a problem anymore ?

**Comment by nono** [comment]
It's aggressive, I'm not sure it's not an issue. But why do you generate so many tokens?

**Comment by cedricmessiant** [comment]
I added an option to be able to control the pool size: https://github.com/cozy/ACH/pull/43 because it  seems that when I ran my migration script on staging it took too many resources
