### ISSUE TITLE
Automatic publication is broken

### ISSUE THREAD

**Issue by ptbrowne** [cozy/ACH#47]
We should have automatic publication via semantic-release.

**Comment by drazik** [comment]
Actually we use semantic-release (https://github.com/cozy/ACH/blob/master/.travis.yml#L13) but it fails (https://travis-ci.org/cozy/ACH/builds/580278468#L557).

It doesn't seem to be configured as recommended: https://travis-ci.org/cozy/ACH/builds/580278468#L557

**Comment by ptbrowne** [comment]
J'ai changé le token sur https://travis-ci.org/cozy/ACH/settings par un token perso.

**Comment by doubleface** [comment]
Ca fonctionne depuis pas mal de temps maintenant
